name: ci
on:
    push:
        branches:
        - master
        - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.x

            - name: Setup Cache ID
              run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

            - name: Cache Dependencies and Build Outputs
              uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-

            - name: Install Dependencies
              run: |
                pip install -r requirements.txt

            - name: Build and Deploy
              env:
                  MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
              run: mkdocs gh-deploy --force
